name: Otra consulta
description: Abre una incidencia que no encaja en las demás categorías.
labels: ["question"]
body:
  - type: textarea
    id: details
    attributes:
      label: Detalles
      description: Incluye todo el contexto necesario para comprender la consulta.
    validations:
      required: true
